
import { Category, CompanySize } from './types';

export const STACK_DATA: Category[] = [
  // Top Row
  {
    title: 'Video',
    gridArea: 'video',
    bgColor: 'bg-fuchsia-800/80',
    textColor: 'text-fuchsia-300',
    shadowColor: 'fuchsia-500',
    tools: [
      { name: 'Loom', sizes: [CompanySize.Startup, CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Sendspark', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Vidyard', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Email Warming',
    gridArea: 'email-warming',
    bgColor: 'bg-violet-800/80',
    textColor: 'text-violet-300',
    shadowColor: 'violet-500',
    tools: [
      { name: 'Instantly', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Smartlead', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
    ],
  },
  {
    title: 'AI Emails',
    gridArea: 'ai-emails',
    bgColor: 'bg-violet-800/80',
    textColor: 'text-violet-300',
    shadowColor: 'violet-500',
    tools: [
      { name: 'Regie.ai', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Lavender.ai', sizes: [CompanySize.Startup, CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'LI Automation',
    gridArea: 'li-automation',
    bgColor: 'bg-fuchsia-800/80',
    textColor: 'text-fuchsia-300',
    shadowColor: 'fuchsia-500',
    tools: [
      { name: 'Dripify', sizes: [CompanySize.Startup] },
      { name: 'Expand', sizes: [CompanySize.Scaleup] },
      { name: 'Heyreach', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Job Changers',
    gridArea: 'job-changers',
    bgColor: 'bg-fuchsia-800/80',
    textColor: 'text-fuchsia-300',
    shadowColor: 'fuchsia-500',
    tools: [
      { name: 'Champify', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'UserGems', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Deanonymize website visitors',
    gridArea: 'deanonymize',
    bgColor: 'bg-indigo-800/80',
    textColor: 'text-indigo-300',
    shadowColor: 'indigo-500',
    tools: [
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'RB2B', sizes: [CompanySize.Scaleup] },
      { name: 'Clearbit Reveal', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: '6Sense', sizes: [CompanySize.Enterprise] },
      { name: 'Factors.ai', sizes: [CompanySize.Scaleup] },
      { name: 'Vector', sizes: [CompanySize.Startup] },
      { name: 'Koala', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Warmly', sizes: [CompanySize.Startup] },
      { name: 'Qualified', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Zoominfo', sizes: [CompanySize.Enterprise] },
    ],
  },
  // Second Row from Top
  {
    title: 'Warm Intros',
    gridArea: 'warm-intros',
    bgColor: 'bg-fuchsia-800/80',
    textColor: 'text-fuchsia-300',
    shadowColor: 'fuchsia-500',
    tools: [
      { name: 'Cabal', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Connect the Dots', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'The Swarm', sizes: [CompanySize.Startup] },
    ],
  },
  {
    title: 'Dialers',
    gridArea: 'dialers',
    bgColor: 'bg-violet-800/80',
    textColor: 'text-violet-300',
    shadowColor: 'violet-500',
    tools: [
      { name: 'Frontspin', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Nooks', sizes: [CompanySize.Scaleup] },
      { name: 'Orum', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'LinkedIn',
    gridArea: 'linkedin',
    bgColor: 'bg-indigo-700/80',
    textColor: 'text-indigo-200',
    shadowColor: 'indigo-400',
    tools: [],
  },
  {
    title: 'Signals',
    gridArea: 'signals',
    bgColor: 'bg-indigo-700/80',
    textColor: 'text-indigo-200',
    shadowColor: 'indigo-400',
    tools: [
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Common Room', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Koala', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Unify', sizes: [CompanySize.Enterprise] },
    ],
  },
  // Central Row
  {
    title: 'Scheduling',
    gridArea: 'scheduling',
    bgColor: 'bg-indigo-800/80',
    textColor: 'text-indigo-300',
    shadowColor: 'indigo-500',
    tools: [
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Cal', sizes: [CompanySize.Startup] },
      { name: 'Calendly', sizes: [CompanySize.Startup, CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Chili Piper', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Outreach', sizes: [CompanySize.Enterprise] },
      { name: 'SalesLoft', sizes: [CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Conversational Intelligence',
    gridArea: 'conv-intel',
    bgColor: 'bg-indigo-700/80',
    textColor: 'text-indigo-200',
    shadowColor: 'indigo-400',
    tools: [
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Attention', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Clari', sizes: [CompanySize.Enterprise] },
      { name: 'Fathom', sizes: [CompanySize.Startup] },
      { name: 'Gong', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Granola', sizes: [CompanySize.Startup] },
      { name: 'Outreach', sizes: [CompanySize.Enterprise] },
      { name: 'SalesLoft', sizes: [CompanySize.Enterprise] },
      { name: 'Scratchpad', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Zoominfo', sizes: [CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Sales Engagement',
    gridArea: 'sales-engagement',
    bgColor: 'bg-indigo-700/80',
    textColor: 'text-indigo-200',
    shadowColor: 'indigo-400',
    tools: [
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Amplemarket', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Clari', sizes: [CompanySize.Enterprise] },
      { name: 'Gong', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'HubSpot', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Outreach', sizes: [CompanySize.Enterprise] },
      { name: 'Salesforce', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'SalesLoft', sizes: [CompanySize.Enterprise] },
      { name: 'Unify', sizes: [CompanySize.Enterprise] },
      { name: 'Zoominfo', sizes: [CompanySize.Enterprise] },
      { name: 'Instantly', note: '(high volume)', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Smartlead', note: '(high volume)', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
    ],
  },
  {
    title: 'Data',
    gridArea: 'data',
    bgColor: 'bg-indigo-700/80',
    textColor: 'text-indigo-200',
    shadowColor: 'indigo-400',
    tools: [
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Clay', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Cognism', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'LeadIQ', sizes: [CompanySize.Scaleup] },
      { name: 'LinkedIn', sizes: [CompanySize.Startup, CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Zoominfo', sizes: [CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Intent Data',
    gridArea: 'intent-data',
    bgColor: 'bg-indigo-800/80',
    textColor: 'text-indigo-300',
    shadowColor: 'indigo-500',
    tools: [
      { name: '6Sense', sizes: [CompanySize.Enterprise] },
      { name: 'Demandbase', sizes: [CompanySize.Enterprise] },
      { name: 'Apollo', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Zoominfo', sizes: [CompanySize.Enterprise] },
      { name: 'Bombora', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Scoring',
    gridArea: 'scoring',
    bgColor: 'bg-indigo-800/80',
    textColor: 'text-indigo-300',
    shadowColor: 'indigo-500',
    tools: [
      { name: 'MadKudu', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Pocus', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Demandbase', sizes: [CompanySize.Enterprise] },
      { name: 'Zoominfo', sizes: [CompanySize.Enterprise] },
    ],
  },
  // Main CRM Block and neighbours
  {
    title: 'Lead Routing',
    gridArea: 'lead-routing',
    bgColor: 'bg-indigo-800/80',
    textColor: 'text-indigo-300',
    shadowColor: 'indigo-500',
    tools: [
      { name: 'Ringlead (Zoominfo)', sizes: [CompanySize.Enterprise] },
      { name: 'Leandata', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'ChiliPiper', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Default*', sizes: [CompanySize.Startup] },
    ],
  },
  {
    title: 'CRM',
    gridArea: 'crm',
    bgColor: 'bg-blue-700/80',
    textColor: 'text-blue-200',
    shadowColor: 'blue-400',
    tools: [
      { name: 'Salesforce', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Hubspot', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Attio*', sizes: [CompanySize.Startup] },
      { name: 'Clarify*', sizes: [CompanySize.Startup] },
      { name: 'Day*', sizes: [CompanySize.Startup] },
    ],
  },
  {
    title: 'Chat',
    gridArea: 'chat',
    bgColor: 'bg-gray-800/80',
    textColor: 'text-gray-300',
    shadowColor: 'gray-500',
    tools: [
      { name: 'Conversica', sizes: [CompanySize.Enterprise] },
      { name: 'Drift', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Intercom', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Qualified', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  // Bottom Row
  {
    title: 'MAP',
    gridArea: 'map',
    bgColor: 'bg-gray-800/80',
    textColor: 'text-gray-300',
    shadowColor: 'gray-500',
    tools: [
      { name: 'HubSpot', sizes: [CompanySize.Startup, CompanySize.Scaleup] },
      { name: 'Inflection.io*', sizes: [CompanySize.Scaleup] },
      { name: 'Marketo (Adobe)', sizes: [CompanySize.Enterprise] },
      { name: 'Pardot (Salesforce)', sizes: [CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Reverse ETL',
    gridArea: 'reverse-etl',
    bgColor: 'bg-gray-800/80',
    textColor: 'text-gray-300',
    shadowColor: 'gray-500',
    tools: [
      { name: 'Census', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Hightouch', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
  {
    title: 'Data warehouse',
    gridArea: 'data-warehouse',
    bgColor: 'bg-gray-800/80',
    textColor: 'text-gray-300',
    shadowColor: 'gray-500',
    tools: [
      { name: 'Big Query (Google)', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Redshift', sizes: [CompanySize.Enterprise] },
      { name: 'Rudderstack', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Segment (Twilio)', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Snowflake', sizes: [CompanySize.Enterprise] },
    ],
  },
  {
    title: 'BI',
    gridArea: 'bi',
    bgColor: 'bg-gray-800/80',
    textColor: 'text-gray-300',
    shadowColor: 'gray-500',
    tools: [
      { name: 'Tableau (Salesforce)', sizes: [CompanySize.Enterprise] },
      { name: 'Looker (Google)', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
      { name: 'Domo', sizes: [CompanySize.Scaleup, CompanySize.Enterprise] },
    ],
  },
];
